"""Report formatters: JSON, Markdown, and HTML."""

from __future__ import annotations

import html
import json
from dataclasses import asdict
from enum import Enum
from typing import Any

from ..core.models import ScanResult, Severity


class _Encoder(json.JSONEncoder):
    def default(self, o: Any) -> Any:
        if isinstance(o, Enum):
            return o.value
        return super().default(o)


def to_json(result: ScanResult, indent: int = 2) -> str:
    """Convert ScanResult to JSON string."""
    data = asdict(result)
    # Convert datetime
    if result.scan_start is not None:
        data["scan_start"] = result.scan_start.isoformat()
    if result.scan_end is not None:
        data["scan_end"] = result.scan_end.isoformat()
    data["score"] = result.score
    return json.dumps(data, cls=_Encoder, indent=indent, ensure_ascii=False)


_SEV_ORDER = [Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM, Severity.LOW, Severity.INFO]
_SEV_COLORS = {
    Severity.CRITICAL: "#b00020",
    Severity.HIGH: "#d32f2f",
    Severity.MEDIUM: "#f9a825",
    Severity.LOW: "#0288d1",
    Severity.INFO: "#757575",
}


def _counts(result: ScanResult) -> dict[Severity, int]:
    counts: dict[Severity, int] = {}
    for v in result.vulnerabilities:
        counts[v.severity] = counts.get(v.severity, 0) + 1
    return counts


def _md_cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def to_markdown(result: ScanResult) -> str:
    """Render a ScanResult as a Markdown report."""
    counts = _counts(result)
    started = result.scan_start.isoformat() if result.scan_start else "n/a"
    lines: list[str] = [
        f"# AllowScanner Report — {result.target_url}",
        "",
        f"- **Domain:** {result.base_domain}",
        f"- **Scanned:** {started}",
        f"- **Duration:** {result.duration_seconds:.1f}s",
        f"- **Security score:** {result.score}/100",
        "- **Findings:** " + "  ".join(f"{s.value}: {counts.get(s, 0)}" for s in _SEV_ORDER),
        "",
    ]

    vulns = sorted(result.vulnerabilities, key=lambda v: v.severity)
    if vulns:
        lines += [
            "## Findings",
            "",
            "| Severity | Finding | Location | CWE | Recommendation |",
            "|---|---|---|---|---|",
        ]
        for v in vulns:
            lines.append(
                f"| {v.severity.value} | {_md_cell(v.name)} | {_md_cell(v.url)} | "
                f"{v.cwe or '—'} | {_md_cell(v.recommendation)} |"
            )
        lines.append("")
    else:
        lines += ["No vulnerabilities found. ✅", ""]

    if result.open_ports:
        lines += ["## Open Ports", "", ", ".join(str(p) for p in result.open_ports), ""]

    if result.technologies:
        lines += ["## Technologies", ""]
        for t in sorted(result.technologies, key=lambda t: t.category):
            ver = f" {t.version}" if t.version else ""
            lines.append(f"- **{t.name}**{ver} ({t.category or 'unknown'})")
        lines.append("")

    cert = result.certificate
    if cert:
        lines += ["## TLS Certificate", ""]
        lines.append(f"- Issuer: {cert.issuer}")
        lines.append(f"- Subject: {cert.subject}")
        lines.append(f"- Negotiated protocol: {cert.protocol}")
        if cert.supported_protocols:
            lines.append(f"- Supported protocols: {', '.join(cert.supported_protocols)}")
        if cert.days_remaining is not None:
            lines.append(f"- Expires in: {cert.days_remaining} days")
        lines.append("")

    if result.dns_records:
        lines += ["## DNS", ""]
        for key, value in result.dns_records.items():
            lines.append(f"- {key}: {value}")
        lines.append("")

    if result.subdomains:
        lines += ["## Subdomains", ""]
        lines += [f"- {s}" for s in result.subdomains]
        lines.append("")

    lines += ["---", "", "_Generated by [AllowScanner](https://github.com/0xgetz/allowScanner)._"]
    return "\n".join(lines)


def to_html(result: ScanResult) -> str:
    """Render a ScanResult as a self-contained HTML report."""
    counts = _counts(result)
    vulns = sorted(result.vulnerabilities, key=lambda v: v.severity)
    started = result.scan_start.isoformat() if result.scan_start else "n/a"
    score = result.score
    score_color = "#2e7d32" if score >= 80 else "#f9a825" if score >= 50 else "#b00020"

    rows = []
    for v in vulns:
        color = _SEV_COLORS.get(v.severity, "#757575")
        rows.append(
            "<tr>"
            f'<td><span class="badge" style="background:{color}">{html.escape(v.severity.value)}</span></td>'
            f"<td>{html.escape(v.name)}</td>"
            f'<td class="mono">{html.escape(v.url)}</td>'
            f"<td>{html.escape(v.cwe or '—')}</td>"
            f"<td>{html.escape(v.recommendation)}</td>"
            "</tr>"
        )
    findings = "\n".join(rows) or '<tr><td colspan="5">No vulnerabilities found ✅</td></tr>'
    summary = " · ".join(f"{s.value} {counts.get(s, 0)}" for s in _SEV_ORDER)
    ports = ", ".join(str(p) for p in result.open_ports) or "—"

    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>AllowScanner Report — {html.escape(result.target_url)}</title>
<style>
body{{font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;margin:0;padding:2rem;line-height:1.5;background:#0d1117;color:#e6edf3}}
.wrap{{max-width:1000px;margin:0 auto}}
h1{{font-size:1.4rem;margin:0 0 .25rem}}
.muted{{color:#8b949e}}
.score{{font-size:2rem;font-weight:700;color:{score_color}}}
table{{width:100%;border-collapse:collapse;margin-top:1rem;font-size:.9rem}}
th,td{{text-align:left;padding:.5rem .6rem;border-bottom:1px solid #30363d;vertical-align:top}}
th{{color:#8b949e;font-weight:600}}
.badge{{color:#fff;border-radius:4px;padding:.1rem .4rem;font-size:.75rem;font-weight:700}}
.mono{{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:.8rem;word-break:break-all}}
.cards{{display:flex;gap:1rem;flex-wrap:wrap;margin:1rem 0}}
.card{{background:#161b22;border:1px solid #30363d;border-radius:8px;padding:.75rem 1rem}}
footer{{margin-top:2rem;color:#8b949e;font-size:.8rem}}
a{{color:#58a6ff}}
</style></head>
<body><div class="wrap">
<h1>🛡️ AllowScanner Report</h1>
<div class="muted">{html.escape(result.target_url)} · {html.escape(result.base_domain)}</div>
<div class="cards">
<div class="card"><div class="muted">Score</div><div class="score">{score}/100</div></div>
<div class="card"><div class="muted">Findings</div><div>{html.escape(summary)}</div></div>
<div class="card"><div class="muted">Open ports</div><div>{html.escape(ports)}</div></div>
<div class="card"><div class="muted">Scanned</div><div>{html.escape(started)}</div></div>
</div>
<table>
<thead><tr><th>Severity</th><th>Finding</th><th>Location</th><th>CWE</th><th>Recommendation</th></tr></thead>
<tbody>
{findings}
</tbody></table>
<footer>Generated by <a href="https://github.com/0xgetz/allowScanner">AllowScanner</a>.</footer>
</div></body></html>"""
